# Generated by ChatGPT on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_created_at_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
