@startuml
!theme toy
skinparam linetype ortho
hide circle
hide stereotype
skinparam entity {
  arrowColor Black
}

entity "1Users" as user {
  * UserID : int
  --
  Username : varchar(150) <<UNIQUE>>
  PasswordHash : varchar(255)
  Email : varchar(255) <<UNIQUE>>
  Name : varchar(255)
  Role : enum (customer, admin)
  Status : enum (active, suspended)
  BehaviorScore : int
}

entity "2TablesBooking" as table {
  * TableID : int
  --
  TableName : varchar(255) <<UNIQUE>>
  Description : text
  -- Optional --
  Capacity : int
  IsActive : boolean
}

entity "3Timeslots" as timeslot {
  * TimeslotID : int
  --
  StartTime : time
  EndTime : time
}

entity "4Games" as game {
  * GameID : int
  --
  GameName : varchar(255)
  Description : text
  Image : varchar(255)
}

entity "5Bookings" as booking {
  * BookingID : int
  --
  UserID : int <<FK>>
  TableID : int <<FK>>
  TimeslotID : int <<FK>>
  BookingDate : date
  PartySize : int
  Status : enum (Pending, Confirmed, Cancelled)
  Notes : text
  CustomerName : varchar(255)
  Phone : varchar(50)
  Email : varchar(255)
  CreatedAt : datetime
  --
  <<UNIQUE(TableID, TimeslotID, BookingDate)>>
}

entity "6BookingItems" as booking_item {
  * BookingItemID : int
  --
  BookingID : int <<FK>>
  GameID : int <<FK>>
}

user ||--o{ booking
table ||--o{ booking
timeslot ||--o{ booking
booking ||--o{ booking_item
game ||--o{ booking_item

@enduml
