@startuml
skinparam state {
  BackgroundColor White
  BorderColor #444
  ArrowColor Black
}

state "ไม่อยู่ในระบบ (Guest)" as GuestState
state "ลูกค้า (Customer)" as CustomerState
state "ผู้ดูแลระบบ (Admin)" as AdminState

state "จัดการโปรไฟล์ (Profile Management)" as ProfileManagement {
    state "ดูข้อมูลส่วนตัว" as ViewProfile
    state "แก้ไขข้อมูล" as EditProfile
}

state "จัดการระบบ (System Management)" as AdminManagement {
    state "จัดการการจอง" as ManageBookings
    state "จัดการข้อมูลลูกค้า" as ManageCustomers
    state "จัดการข้อมูลโต๊ะ" as ManageTables
    state "จัดการข้อมูลเกม" as ManageGames
    state "ตั้งค่าระบบ" as ConfigureSystem
}

state "การจอง (Booking)" as BookingProcess {
    state "เลือกวัน" as SelectDate
    state "เลือกโต๊ะและเวลา" as SelectTable
    state "เลือกเกม(Button 10.1)" as SelectGame
    state "ยืนยันการจอง(Button 11.1)" as ConfirmBooking
    state "การจองสำเร็จ #12" as BookingSuccess
    state "การจองล้มเหลว" as BookingFailed
}

[*] --> GuestState : เริ่มต้น

GuestState --> CustomerState : เข้าสู่ระบบ(Button login 1.3)
GuestState --> GuestState : ลืมรหัสผ่าน (Forget Password 1.1)

CustomerState --> ProfileManagement : เข้าสู่โปรไฟล์ (Profile 7.1)
ProfileManagement --> ViewProfile : ดูข้อมูล
ProfileManagement --> EditProfile : แก้ไขข้อมูลส่วนตัว (Button 13.1)
EditProfile --> ViewProfile : บันทึก (Button 13.1.1)

CustomerState --> CustomerState : ดูประวัติการจอง (Button 7.3)
CustomerState --> GuestState : ออกจากระบบ (Button 13.2)

AdminState --> AdminManagement : เข้าสู่ระบบจัดการ (Button 15.1)
AdminManagement --> ManageBookings : จัดการรายการจอง (Button 16.1)
AdminManagement --> ManageCustomers : จัดการข้อมูลลูกค้า (Button 16.3)
AdminManagement --> ManageTables : จัดการข้อมูลโต๊ะ (Button 16.2)
AdminManagement --> ManageGames : จัดการข้อมูลเกม (Button 16.4)
AdminManagement --> ConfigureSystem : จัดการ Configure ระบบ #16

AdminState --> GuestState : ออกจากระบบ

CustomerState -[hidden]-> AdminState

CustomerState --> BookingProcess : เริ่มจองโต๊ะ (Button 7.2)

BookingProcess --> SelectDate
SelectDate --> SelectTable : เลือกวัน (Button 8.1)
SelectTable --> SelectGame : เลือกโต๊ะและเวลา (Button 9.1)
SelectGame --> ConfirmBooking : เลือกเกม (Button 10.3)
ConfirmBooking --> BookingSuccess : ยืนยันสำเร็จ
ConfirmBooking --> BookingFailed : **(Error)** จองซ้ำซ้อน

BookingSuccess --> CustomerState : กลับสู่หน้าหลัก (Home 12.1)
BookingFailed --> SelectDate : ลองใหม่

@enduml